### ISSUE TITLE
Cloud IAM Permission injection from the config

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#12]
Currently there is no way to add cloud IAM permissions to the cluster or pods via the config file:

So for example, if you want to append permissions to this list, you can do that after the project is generated, but then you can auto update the QHub as it will override the custom changes you would make.

https://github.com/Quansight/qhub-ops/blob/e5dd52df558c2c4eb805594b6ae574f12e0986a1/qhub_ops/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/gcp.tf#L22

One solution is to create a section in config.yml that adds permission which can be appended to the list.

**Comment by brl0** [comment]
IIUC, I think this would be useful.

**Comment by viniciusdc** [comment]
@aktech @costrouc Have we fixed that within the latest releases?

**Comment by brl0** [comment]
No, it hasn't been fixed yet, since we just had to deal with this again on a new deployment.  Here is the documentation on what needs to be done following deployment to give IAM users access to the cluster: https://aws.amazon.com/premiumsupport/knowledge-center/eks-kubernetes-object-access-error/

As @aktech suggested, I think a section for adding IAM users in the config file would be great.
Something maybe like:

```yaml
amazon_web_services:
  ...
  iam_users:
    arn:aws:iam::XXXXXXXXXXXX:user/testuser1
    arn:aws:iam::XXXXXXXXXXXX:user/testuser2
```

I guess another alternative could be to add a field to the users section:
```yaml
security:
  ...
  users:
    example-user:
      primary_group: admin
      secondary_groups:
      - users
      uid: 1000
      arn: arn:aws:iam::XXXXXXXXXXXX:user/testuser1
```
