### ISSUE TITLE
[BUG] - Add pip packages to environment section of qhub-config breaks deployment

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1207]
### OS system and architecture in which you are running QHub

Ubuntu (GitHub Actions)

### Expected behavior

Adding a pip package to an environment in the `qhub-config.yaml` should build the environment.

This package was added to qhub-deployment-quansight-beta.

```
  environment-eae.yaml:
    name: eae
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - numpy
    - pandas
    - pip:    <-- cause of the issue
      - requests
```

### Actual behavior

Attempting to deploy the `qhub-config.yaml` with new environment listed above results in a failed deployment:

```
INFO:qhub.provider.terraform:terraform apply directory=stages/07-kubernetes-services
...
...
[terraform]: │ Error: Invalid value for module argument
[terraform]: │ 
[terraform]: │   on jupyterhub.tf line 103, in module "jupyterhub":
[terraform]: │  103:   conda-store-environments = var.conda-store-environments
[terraform]: │ 
[terraform]: │ The given value is not suitable for child module variable
[terraform]: │ "conda-store-environments" defined at
[terraform]: │ modules/kubernetes/services/jupyterhub/variables.tf:114,1-36: all map
[terraform]: │ elements must have the same type.
```

### How to Reproduce the problem?

In the environment section of the `qhub-config.yaml`, add a pip package to be included to a new environment or to an existing one. Then redeploy.

This seems to also be an issue for users adding the environment directly from the `conda-store`
