### ISSUE TITLE
[BUG] - Dashboard environment might be broken

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1229]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

- We should be able to import `panel` and use it without problems to deploy dashboards on QHub

### Actual behavior

When executing the simple example below, we get the following error message:
```
ImportError: cannot import name 'Markup' from 'jinja2' (/home/conda/filesystem/.../site-packages/jinja2/__init__.py)
```

```python
import panel
panel.extension()

content = panel.pane.Markdown('''
# Hello World

This is some content
''')
```
The errors seem to be related to a recent release of Jinja2, see relevant issue https://github.com/holoviz/panel/issues/3257 which modifies how some of its module's imports work (see relevant changes in [here](https://jinja.palletsprojects.com/en/3.1.x/changes/#:~:text=Markup%20and%20escape%20should%20be%20imported%20from%20MarkupSafe.)).
A new version of `panel` was released recently (0.12.7) which addresses this issue, so we should just update the pins.

### How to Reproduce the problem?

- Run the dashboard example presented on Qhub docs, be aware that this error heavily depends on the final environment package constraints found during environment build/solution. So the above error will not be present if the version of `panel` found is lesser than (`3.1.0`)

### Versions and dependencies used.

Current Dashboard environemt yaml
```yaml
channels:
- conda-forge
dependencies:
- python==3.9.7
- ipykernel==6.4.1
- ipywidgets==7.6.5
- qhub-dask==0.3.13
- param==1.11.1
- python-graphviz==0.17
- matplotlib==3.4.3
- panel==0.12.4
- voila==0.2.16
- streamlit==1.0.0
- dash==2.0.0
- cdsdashboards-singleuser==0.6.0
name: dashboard
prefix: null
```

### Compute environment

GCP

### Integrations

conda-store
