### ISSUE TITLE
[Qhub] - Customization for navigation bar does not take effect

### ISSUE THREAD

**Issue by ychen-ot** [Quansight/qhub#1277]
### OS system and architecture in which you are running QHub

Digital Ocean Kubenetes deployment with QHub 0.4

### Expected behavior

Adding a theme for jupyter hub  does takes effect.

### Actual behavior

When deployed, I see:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/93157550/167913164-105800a8-c6d2-4d42-9f81-39bebc9f6ae3.png">

If I highlight the text - I can see that all menu items are available.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/93157550/167913311-7ddbeba1-5572-4e3b-abd1-bb79a2edc9c8.png">

### How to Reproduce the problem?

Adding a theme in yaml.
```
theme:
  jupyterhub:
    hub_title: QHUB Studio
    hub_subtitle: subtitle 
    primary_color: '#FFFFFF'
    secondary_color: '#FFFFFF'
    accent_color: '#0C88FF'
    text_color: '#000000'
    h1_color: '#000000'
    h2_color: '#000000'
    navbar_text_color: '#000000'
    navbar_hover_color: '#0C88FF'
```

### Versions and dependencies used.

Enterprise Qhub - 0.4.1 

### Compute environment

Digital Ocean

### Integrations

dashboards

### Anything else?

Qhub version starts at v0.4 , then upgrade to v0.4.1 then upgraded for Enterprise QHub. 
For the 0.4 version, we did customize the theme.  Maybe this is an upgrade issue.

**Comment by viniciusdc** [comment]
Hi, @ychen-ot thanks for opening this issue, and letting us know about this usage. Do you have a screenshot of the customized theme when you were using `v0.4.0`? Are there any other extra settings to style/layout/theme that you did besides the ones present in your `qhub-config` above?

**Comment by ychen-ot** [comment]
The other piece that looks weird is the radio button.  The selected button disappeared.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/93157550/167944655-704c4d77-c159-448c-9e17-41461cb5d506.png">

We had customized it in the 0.3.x then 0.4 release., The customization was below, and that worked properly.  No other customization that I am aware of / or remember
```
theme:
  jupyterhub:
    hub_title: Title
    hub_subtitle: subtitle
    logo: path_to_logo
    primary_color: '#FFFFFF'
    secondary_color: '#FFFFFF'
    accent_color: '#0C88FF'
    text_color: '#000000'
    h1_color: '#000000'
    h2_color: '#000000'
```

**Comment by viniciusdc** [comment]
Very strange indeed, I will have a look. Thanks for the details, btw, just to be sure, what are the current docker image versions in your `qhub-config` right now? does it match the currently installed version?

**Comment by viniciusdc** [comment]
Hi @ychen-ot, I've made deployment of qhub with the mentioned style changes, but I wasn't able to replicate the mentioned behavior. Which Browser are you using, maybe there might be a version incompatibility with the CSS styles? 

![image](https://user-images.githubusercontent.com/51954708/168317227-d7265b7f-47d9-4e45-b192-6ac48200cf82.png)

**Comment by ychen-ot** [comment]
@viniciusdc 
I tested in both Chrome and FF / and both are showing this.  Is there something to check in the deployed code?  Maybe there were some leftover thing from previous installation?

**Comment by ychen-ot** [comment]
It is remote.

**Comment by viniciusdc** [comment]
Also, if you have access to your cluster deployment (k9s) you can inspect if the theme settings are correctly assigned to Jupyterhub by inspecting the hub `configmap`.

**Comment by viniciusdc** [comment]
> Thanks. I'll try the suggestion relating to redeploy. Tho, does it impact the applications that I currently have deployed ?

No, if you are not changing the state of the files (this is, not changing any config) it will just refresh the files with the same state.

**Comment by viniciusdc** [comment]
> Thanks. I'll try the suggestion relating to redeploy. Tho, does it impact the applications that I currently have deployed ?

I would first switch back to the default theme, then redeploy to check if that works (doing this first would show us if there is any issue with Qhub itself). If there is no issue with the theme then we will not need to delete anything

**Comment by MaxTechniche** [comment]
@viniciusdc @ychen-ot I've done the steps above. In terms of the color, I believe we just had bad colors set up. We had the title bar being white with white text... yeah. So I was able to fix that.

I'm unsure about the subtitle, logo, and welcome message. I'm not sure where they are supposed to show up or what they change.

**Comment by ychen-ot** [comment]
@MaxTechniche Thank you for testing.  What you are saying is that - b/c the text color is white , and b/c nav bar itself is white, that it was a bad color setup. 
```
navbar_text_color: '#000000'
```

@viniciusdc - qq for you - is there documentation on themes / adjustment ?
We also still not able to see logo and welcome messages.  If you need that in a separate defect ,  I can create one

Thanks

**Comment by viniciusdc** [comment]
> @MaxTechniche Thank you for testing. What you are saying is that - b/c the text color is white , and b/c nav bar itself is white, that it was a bad color setup.
> 
> ```
> navbar_text_color: '#000000'
> ```
> 
> @viniciusdc - qq for you - is there documentation on themes / adjustment ? We also still not able to see logo and welcome messages. If you need that in a separate defect , I can create one
> 
> Thanks

@ychen-ot @MaxTechniche sorry for the late reply, my current understanding of the issue is that the `ent-qhub-jupyterhub-theme` that is installed within your qhub version might be conflicting with the default configuration of Qhub. We are working on obtiaonoig more infrooamtion on this end c.c @iameskild. 

> @viniciusdc - qq for you - is there documentation on themes / adjustment ?
We also still not able to see logo and welcome messages. If you need that in a separate defect , I can create one

@ychen-ot About this, we only have a short mention about customization [here in the docs](https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=theme#customizing-jupyterhub-theme), there is also an advance section for direct customization with the configurations [citted here](https://docs.qhub.dev/en/stable/source/admin_guide/troubleshooting.html?highlight=theme#jupyterhub-theme) (but I think this might generate a conflicting behavior)

About the logo and welcome message you commented, are you passing the variables in the `qhub-config.yaml` with the appropriate values? e.g.

```yaml
theme:
  jupyterhub:
    hub_title: <content>
    hub_subtitle: <content>
    welcome: |
      <your welcome message>
    logo: <https://your-domain/url-to-your-logo>
```
