### ISSUE TITLE
[ENH] Update trigger settings for local Kubernetes test

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1286]
I am opening this issue as a matter of discussion. The current trigger aspect of the Kubernetes test is the following:

```yaml
on:
  pull_request:
    paths:
      - ".github/workflows/kubernetes_test.yaml"
      - "tests/**"
      - "tests_deployment/**"
      - "tests_e2e/**"
      - "scripts/**"
      - "qhub/**"
      - "setup.cfg"
      - "pyproject.yoml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/kubernetes_test.yaml"
      - "tests/**"
      - "tests_deployment/**"
      - "tests_e2e/**"
      - "scripts/**"
      - "qhub/**"
      - "setup.cfg"
      - "pyproject.yoml"
```
Though it does its work on validating that any change made into qhub infrastructure-related config is fully* tested -- by fully I mean an end-to-end deployment for Minikube Qhub. This sometimes can become a long waiting process over changes that are not entirely subject to a Qhub deployment. For example, in this recent https://github.com/Quansight/qhub/pull/1282 if you look at the changes, you will see that there is no need for a full deployment of Qhub (its contrapositive to test this) in this case.

My main points over the current structure are:
- It takes a long waiting process to get a green stage for merging,
- It's using our own resources for this test, so reducing the usage is appreciated when it's not really needed
- Is inconvenience and contra-productive when the changes really do not affect terraform code itself (remember that we do have the integration tests as well)
- Not targeting the Python parts in this full deploy test, would help us create better specific Pytest scenarios to test using only python-based actions (which run much faster)

So I would like to change the above trigger conditions to only trigger by direct changes in the package configuration or the terraform stages:

```yaml
on:
  pull_request:
    paths:
      - ".github/workflows/kubernetes_test.yaml"
      - "qhub/template/stages/*"
      - "setup.cfg"
      - "pyproject.yoml"
```

Would like to know what everyone think
