### ISSUE TITLE
Hyphens in github usernames cause github actions to fail

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#152]
The symptoms of this bug are documented in #150

**Comment by rsignell-usgs** [comment]
@dharhas and @tylerpotts, yipes that's pretty harsh.   I'm definitely not changing my github username (I can't, actually due to USGS policy).    But I guess I could create a new github account/username just for qhub deployment?  

So this is a known general limitation of github actions, or just something in one of your scripts that needs to be modified to allow for hyphenated names?

**Comment by dharhas** [comment]
I think it's a general GitHub actions issue. I've found similar problems googling but not a clear resolution.

**Comment by dharhas** [comment]
@tylerpotts could this be a jinja template issue evaluating the hyphen as a subtraction?

**Comment by dharhas** [comment]
@rsignell-usgs can you give one or two of us access to your repo to look at logs etc?

**Comment by rsignell-usgs** [comment]
@dharhas and @tylerpotts , I've invited both of you.   Thanks for taking a look!

**Comment by tylerpotts** [comment]
> @tylerpotts could this be a jinja template issue evaluating the hyphen as a subtraction?

Yes I think it could be. We'll have to do some digging to be sure

**Comment by dharhas** [comment]
It is failing on this:

```
jobs:
  build:
    name: qhub
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
```

seems like this should be testable outside of qhub in a simple repo and might be an issue with the upstream github-action.
