### ISSUE TITLE
Spot Instances /  Preemptible instances

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#193]
Example GCP config below:
```
google_cloud_platform:
  node_groups:
    spot-high-memory:
      instance: e2-highmem-8
      min_nodes: 0
      max_nodes: 10
      preemptible: true
profiles:
  dask_worker:
    "Spot Large Worker":
      worker_cores_limit: 8
      worker_cores: 7
      worker_memory_limit: 57G
      worker_memory: 57G
      scheduler_memory: 57G
      image: "quansight/qhub-dask-worker:4c8c28332be1fde32f786c54a5961b5f3d789e16"
      scheduler_extra_pod_config:
        nodeSelector:
          "cloud.google.com/gke-nodepool": spot-high-memory
      worker_extra_pod_config:
        nodeSelector:
          "cloud.google.com/gke-nodepool": spot-high-memory
```

Configuration for AWS still requires investigation
