### ISSUE TITLE
Additional config validation checks

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#209]
Added the following validation checks to QHub:
- [] multiple users with the same `uid`
- [] multiple JupyterHub profiles set as default
- [] multiple environments with the same name

**Comment by brl0** [comment]
I still think these would probably be helpful and sensible validation checks.

**Comment by viniciusdc** [comment]
Hi @brl0, thanks for opening this issue. Currently QHub is already handling the duplicate environment check by [`ruamel.yaml.safe_load` validation](https://github.com/Quansight/qhub/blob/53024842cde5dec63b0d249239af0f2b0350a092/qhub/cli/deploy.py#L55). I've created a new step during the `verify(config)` process in the QHub deployment to check the user ids's duplication; 
```python
@validator('users', pre=True)
    def validate_uderids(cls, value):
        # raise ValueError if duplicated
        return check_user_ids(value)
```
Could you give more details about the multiple default jupyterhub profiles issue commented above?

**Comment by brl0** [comment]
@viniciusdc, thanks for following up on this.

To clarify, I just noticed that I incorrectly indicated the JupyterHub profiles, but actually meant jupyterlab.

The jupyterlab instance profiles are defined under the `profiles` key as below:
```yaml
profiles:
  jupyterlab:
  - display_name: Large Instance
    description: Stable environment with 16 cpu / 128 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 15.5
      cpu_guarantee: 12
      mem_limit: 120G
      mem_guarantee: 96G
      image: quansight/qhub-jupyterlab:v0.3.11
      node_selector:
        "eks.amazonaws.com/nodegroup": "user_worker"
```

When copying this profile to create additional instance types, it is easy to accidentally forget to change the `default` attribute to only have one default, which can cause some confusion.  So I think it would be nice to ensure only one jupyterlab profile has `default: true`.  As you might guess, this issue was encountered the hard way.
