### ISSUE TITLE
150cpu/3.4TB RAM user instance: Add user option to change jupyterhub timeout greater than 300 seconds

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#244]
## Description
When spinning up massive user instances on GCP (IE 150 vcpu, 3.4TB memory) it takes longer than 300 seconds for the virtual machine to spin up. This causes the spawner to fail with a time out message. Immediately attempting to spawn again is successful, because the virtual machine has already begun to spin up.

## Suggestion
Add an option in qhub-config to increase the time out. Ideally at the nodegroup level.

## Context
Nice to have, not critical.

## Additional context
Here's how to configure the option for a gigantic [preemptible instance](https://cloud.google.com/compute/docs/instances/preemptible) on GCP

```
google_cloud_platform:
  project: **private**
  region: us-central1
  zone: us-central1-c
  availability_zones:
    - us-central1-c
  kubernetes_version: "1.14.10-gke.31"
  node_groups:
    user-gigantic:
      instance: m1-ultramem-160
      min_nodes: 0
      max_nodes: 5
      preemptible: true
profiles:
  jupyterlab:
    - display_name: Gigantor Large Instance (~$5/hr)
      description: Stable environment with 158 cpu / 3500 GB ram
      kubespawner_override:
        cpu_limit: 150
        cpu_guarantee: 150
        mem_limit: 3400G
        mem_guarantee: 3400G
        image: "gcr.io/geoencoding-datu-1571679200174/datum-prod/qhub-jupyterlab:9f85f6ca480b28b451c3702d733318938798b8c2"
        node_selector:
          "cloud.google.com/gke-nodepool": "user-gigantic"
```
