### ISSUE TITLE
Make jupyterhub culler configurable

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#476]
Currently the built in

```
cull:
  enabled: true
  timeout: 1800 # cull after 30min of inactivity
  every: 600
```

We are finding (obviously) that this time limit is not convenient for users
