### ISSUE TITLE
Removing the need to uids/gids to be set

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#496]
Okay see is an interesting problem and interested if people have ideas on the subject.

Problem:

In QHub we want the ability for users to easily share files between each-other while enforcing some kind of access control in Linux. The most obvious form of access control is the Linux permission system: (r)ead, (w)rite, e(x)ecute on user, group, all.

Currently in QHub we have a mapping of usernames to uids, and groups to gids:

```yaml
  users:
    chriso:
      uid: 1000
      primary_group: admin
      secondary_groups:
        - users
        - fungroup
    tylerp:
      uid: 1001
      primary_group: users
  groups:
    admin:
      gid: 100
    users:
      gid: 101
```

As you can see we have to ask the users to manually specify uids and gids for all groups. This is TEDIOUS and error prone and just not a fun user experience for adding new users.

When a kubernetes pod is launched for the given user several things happen (lets assume the user is =chriso=).

 - jupyterlab is launched with uid=1000, primary gid=100, secondary_groups=[101]
 - a nfs volume is mounted at =/home/shared=

Because the user has a well defined uid, gid, etc. we can easily secure the access to the nfs volume.

Ideas:

1. Could we remove the need to specify a UID/GID for the users/groups?

UIDS and GIDS have =2^32 - 2= values. We also can't have roughly the first 32k ids. Thus we still have around 2e9 possible values.

hash(username) -> uid

Suppose a predictable uid and gid. What would be hash collision likelyhood?

Would a hash collision be that bad? If we are careful to **only** mount the nfs paths the user has access too the worst that could happen is that they could write as a uid/gid that another user reuses.

What would this mapping function that minimizes collisions look like?

**Comment by dharhas** [comment]
some discussion here. 

https://stackoverflow.com/questions/16521148/string-to-unique-integer-hashing/16521671

**Comment by danlester** [comment]
Another possibility could be to host a simple "uid server" that returns the next available uid given a new username, or returns the cached uid if the username was seen before.

Maybe a bit of an effort by the time it's got associated persistent storage - but could possibly be squeezed into the NFS server pod on a special folder mount on the existing disk.

**Comment by costrouc** [comment]
Found some docs from redhat:
 - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/identity_management_guide/managing-unique_uid_and_gid_attributes

I think their approach is simple and also avoids the possibility of collisions:

```yaml
users:
  costrouc:
      uid: 100010
  collidinguser
```

We just use a simple hash function e.g. `sha256(username) -> first 20 bits -> 2^20 ~= 1 million ids. So that the ids are evenly spread in the interval.

On the QHub render step we compute all the `username -> id` mappings. If there is a collision we throw an error saying `costrouc` with dynamic id=1001020 collided with `collidinguser` with dynamic id=10001020. Please specify a static uid mapping for either user that does not collide. 

The change of collision is rare and allows us to no longer require ids for the usernames and groups.

I could see this enabling us to specifiy e.g.

```yaml
users:
  "*.quansight.com":
      primary_group: quansight
      secondary_groups:
          - users
```

For example and we could have a regex for groups of users and assigning permissions to these users. The one hole I can see with this is that two regex usernames might have the same dynamic uid. However we can guarantee that the gids will never collide since groups are not regexes. Thus the worst that could happen is that a user writes a file to a shared folder with a matching uid of another user. I consider this to be harmless and rare.

**Comment by dharhas** [comment]
This sounds like a decent approach. "*.quansight.com" <- is very powerful.

**Comment by dharhas** [comment]
```yaml
users:`
  "*.quansight.com":
      primary_group: quansight
      secondary_groups:
          - users
groups:
  `myproject`: user1, user2 etc
```

then you could do something like ☝️
