### ISSUE TITLE
Test if the image tag is required on instance definitions

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#611]
Test to see if the default images are required for the instance definitions block in qhub-config.yaml

```
  - display_name: Large Instance
    description: Stable environment with 8 cpu / 32 GB ram
    kubespawner_override:
      cpu_limit: 8
      cpu_guarantee: 7.25
      mem_limit: 32G
      mem_guarantee: 24G
      image: quansight/qhub-jupyterlab:v0.3.11
```

- [ ] If not required, remove the image tag in qhub-config.yaml when running `qhub init`
