### ISSUE TITLE
[enhancement] Unify configuration JupyterLab and Dask Worker profiles

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/qhub#752]
## Description
Dask Worker and the JupyterLab profiles require very similar information but are specified differently in `qhub-config.yml`. `profiles.jupyterlab` is a list of objects with a name, description, default flag, and a dict of instance info. In contrast `profiles.dask_worker` is a dict whose keys are instance sizes and whose values are dicts containing instance info.

Does it make sense to give both types of  profiles a common set of configuration settings? i.e. both `jupyterlab` and `dask_worker` sections are treated the same way, something like this:

```
qhub-config.yml
============

...

profiles:
  - display_name: Small Instance
    profile_type: jupyterlab
    description: Stable environment with 1 cpu / 8 GB ram
    default: true
    cpu_limit: 1
    cpu: 0.75
    mem_limit: 8G
    mem: 5G
    groups: admins
  - display_name: Small Instance
    profile_type: dask_worker
    description: Dask environment with 1 cpu / 4 GB ram
    default: true
    cpu_limit: 1
    cpu: 0.75
    mem_limit: 4G
    mem: 2G

...
```

## Context
Although this enhancement wouldn't change any external-facing behavior, it would make the profiles section simpler to write, document, and understand.
