### ISSUE TITLE
[enhancement] configure prefect agent labels and environment variables

### ISSUE THREAD

**Issue by jhamman** [Quansight/qhub#764]
## Description

I would like to set [labels](https://docs.prefect.io/orchestration/agents/kubernetes.html#labels) and [environment variables](https://docs.prefect.io/orchestration/agents/kubernetes.html#environment-variables) on my prefect agents. Is this possible today? Or does this require a new feature in qhub?

## Suggestion
Perhaps the prefect configuration section could look something like this:

```yaml
prefect:
  enabled: true
  labels: ["dev", "staging"]
  env_vars: {"KEY": "VALUE", "KEY2": "VALUE2"}
```

## Context
Our prefect cloud account has multiple agents attached to it. Exposing labels and env_vars via the qhub config would allow us to preferentially direct flows to the correct agent.
