### ISSUE TITLE
[enhancement] add option to specify username key in auth0 specification

### ISSUE THREAD

**Issue by jhamman** [Quansight/qhub#765]
## Description
I would like to use auth0 for authentication in my hub but I'd prefer to use a non-default username key. [Z2JH](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#auth0) exposes the helpful `username_key` which can be extracted from the Auth0 profile.  
## Suggestion

I think the fix here would be as simple as adding the `username_key` under `authentication.config`:

```yaml
security:
  authentication:
    type: Auth0
    config:
      ...
      username_key: nickname
```

Then extracting this key in place of the default userid. 

## Context

We are using Auth0 connected to GitHub OAuth. I'd prefer to use our GitHub user ids, instead of the default (email address) username.
