### ISSUE TITLE
Documentation on memory and cpu requirements for base qhub cluster

### ISSUE THREAD

**Issue by jhamman** [Quansight/qhub#766]
## Describe the bug

I'm working on a qhub deployment in Azure Kubernetes. After successfully deploying qhub, I'm seeing many Evicted conda-store pods. Based on my reading of the pod eviction message, it seems the conda-store pods are not requesting sufficient memory.

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
...
  Warning  Evicted                 7s                   kubelet                  The node was low on resource: memory. Container nfs-server was using 165800Ki, which exceeds its request of 0. Container conda-store was using 4757848Ki, which exceeds its request of 0.
  Normal   Killing                 7s                   kubelet                  Stopping container conda-store
  Normal   Killing                 7s                   kubelet                  Stopping container nfs-server
```

more details below.

## How can we help?
Help us help you.
* What are you trying to achieve?

  Generate a healthy qhub deployment.

* How can we reproduce the problem?

  See the following `qhub-config.yaml` (secrets redacted):

  <details>

   ```yaml
  project_name: hubeu
  provider: azure
  domain: <DOMAIN>
  certificate:
    type: lets-encrypt
    acme_email: REDACTED
    acme_server: https://acme-v02.api.letsencrypt.org/directory
  security:
    authentication:
      type: GitHub
      config:
        client_id: REDACTED
        client_secret: REDACTED
        oauth_callback_url: https://<DOMAIN>/hub/oauth_callback
    users:
      jhamman:
        uid: 1000
        primary_group: admin
        secondary_groups:
        - users
    groups:
      users:
        gid: 100
      admin:
        gid: 101
  default_images:
    jupyterhub: quansight/qhub-jupyterhub:v0.3.12
    jupyterlab: quansight/qhub-jupyterlab:v0.3.12
    dask_worker: quansight/qhub-dask-worker:v0.3.12
    dask_gateway: quansight/qhub-dask-gateway:v0.3.12
    conda_store: quansight/qhub-conda-store:v0.3.12
  storage:
    conda_store: 100Gi
    shared_filesystem: 500Gi
  theme:
    jupyterhub:
      hub_title: MY HUB
      hub_subtitle: ""
      welcome: ""
      logo: /hub/custom/images/jupyter_qhub_logo.svg
      primary_color: '#1B1E23'
      secondary_color: '#1B1E23'
      accent_color: '#EB9755'
      text_color: '#1B1E23'
      h1_color: '#1B1E23'
      h2_color: '#1B1E23'
  cdsdashboards:
    enabled: true
    cds_hide_user_named_servers: false
    cds_hide_user_dashboard_servers: false
  ci_cd:
    type: github-actions
    branch: main
  terraform_state:
    type: remote
  namespace: qhub
  azure:
    project: carbonplan
    region: West Europe
    kubernetes_version: 1.18.19
    node_groups:
      general:
        instance: Standard_D2_v3
        min_nodes: 1
        max_nodes: 2
      user:
        instance: Standard_D16_v3
        min_nodes: 0
        max_nodes: 5
      worker:
        instance: Standard_D16_v3
        min_nodes: 0
        max_nodes: 50
    storage_account_postfix: hycw9t6o
  profiles:
    jupyterlab:
    - display_name: Small Instance
      description: Stable environment with 1 cpu / 4 GB ram
      default: true
      kubespawner_override:
        cpu_limit: 4
        cpu_guarantee: 3.75
        mem_limit: 16G
        mem_guarantee: 12G
        image: quansight/qhub-jupyterlab:v0.3.12
    - display_name: Medium Instance
      description: Stable environment with 2 cpu / 8 GB ram
      kubespawner_override:
        cpu_limit: 8
        cpu_guarantee: 7
        mem_limit: 32G
        mem_guarantee: 24G
        image: quansight/qhub-jupyterlab:v0.3.12
    dask_worker:
      Small Worker:
        worker_cores_limit: 1
        worker_cores: 0.75
        worker_memory_limit: 4G
        worker_memory: 2.5G
        worker_threads: 1
        image: quansight/qhub-dask-worker:v0.3.12
      Medium Worker:
        worker_cores_limit: 2
        worker_cores: 1.5
        worker_memory_limit: 8G
        worker_memory: 5G
        worker_threads: 2
        image: quansight/qhub-dask-worker:v0.3.12
  environments:
    environment-dask.yaml:
      name: dask
      channels:
      - conda-forge
      dependencies:
      - python
      - ipykernel
      - ipywidgets
      - qhub-dask ==0.3.12
      - python-graphviz
      - numpy
      - numba
      - pandas
    environment-dashboard.yaml:
      name: dashboard
      channels:
      - conda-forge
      dependencies:
      - python
      - ipykernel
      - ipywidgets >=7.6
      - qhub-dask ==0.3.12
      - param
      - python-graphviz
      - matplotlib >=3.3.4
      - panel >=0.10.3
      - voila >=0.2.7
      - streamlit >=0.76
      - dash >=1.19
      - cdsdashboards-singleuser >=0.5.7
   ```
  </details>

* What is the expected behaviour?

  Conda store pods should not be evicted after deployment.

* And what is currently happening?

  Shortly after deployment, conda-store pods start getting evicted. 

* Any error messages?

  See below for the following pod details / logs:

<details>

<summary>pod describe </summary>

```
Name:           qhub-conda-store-7b74494c76-2gcdb
Namespace:      qhub
Priority:       0
Node:           aks-general-41025623-vmss000000/
Start Time:     Tue, 17 Aug 2021 12:06:46 -0700
Labels:         pod-template-hash=7b74494c76
                role=qhub-conda-store
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: memory. Container nfs-server was using 165800Ki, which exceeds its request of 0. Container conda-store was using 4757848Ki, which exceeds its request of 0.
IP:
IPs:            <none>
Controlled By:  ReplicaSet/qhub-conda-store-7b74494c76
Containers:
  conda-store:
    Image:      quansight/qhub-conda-store:v0.3.12
    Port:       <none>
    Host Port:  <none>
    Command:
      python
      /opt/conda-store/conda-store.py
      -e
      /opt/environments
      -o
      /home/conda/environments
      -s
      /home/conda/store
      --uid
      0
      --gid
      0
      --permissions
      775
    Environment:  <none>
    Mounts:
      /home/conda from nfs-export-fast (rw)
      /opt/environments from conda-environments (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tbtqj (ro)
  nfs-server:
    Image:        gcr.io/google_containers/volume-nfs:0.8
    Ports:        2049/TCP, 20048/TCP, 111/TCP
    Host Ports:   0/TCP, 0/TCP, 0/TCP
    Environment:  <none>
    Mounts:
      /exports from nfs-export-fast (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tbtqj (ro)
Volumes:
  nfs-export-fast:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  qhub-conda-store-storage
    ReadOnly:   false
  conda-environments:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      conda-environments
    Optional:  false
  default-token-tbtqj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tbtqj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   NotTriggerScaleUp       12m                  cluster-autoscaler       pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max node group size reached, 2 node(s) didn't match node selector
  Warning  FailedScheduling        7m13s (x7 over 12m)  default-scheduler        0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/memory-pressure: }, that the pod didn't tolerate.
  Normal   Scheduled               7m2s                 default-scheduler        Successfully assigned qhub/qhub-conda-store-7b74494c76-2gcdb to aks-general-41025623-vmss000000
  Normal   SuccessfulAttachVolume  6m57s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-097c5342-efb0-438a-b4b1-4ff34465f51d"
  Normal   Pulled                  6m44s                kubelet                  Container image "quansight/qhub-conda-store:v0.3.12" already present on machine
  Normal   Created                 6m44s                kubelet                  Created container conda-store
  Normal   Started                 6m43s                kubelet                  Started container conda-store
  Normal   Pulled                  6m43s                kubelet                  Container image "gcr.io/google_containers/volume-nfs:0.8" already present on machine
  Normal   Created                 6m43s                kubelet                  Created container nfs-server
  Normal   Started                 6m42s                kubelet                  Started container nfs-server
  Warning  Evicted                 28s                  kubelet                  The node was low on resource: memory. Container nfs-server was using 165800Ki, which exceeds its request of 0. Container conda-store was using 4757848Ki, which exceeds its request of 0.
  Normal   Killing                 28s                  kubelet                  Stopping container conda-store
  Normal   Killing                 28s                  kubelet                  Stopping container nfs-server
```
</details>

<details>

<summary> nfs-server log </summary>

```
Serving /exports
Serving /
rpcinfo: can't contact rpcbind: : RPC: Unable to receive; errno = Connection refused
Starting rpcbind
exportfs: / does not support NFS export
NFS started
```
</details>

<details>

<summary> conda-store log </summary>

```
[2021-08-17 19:07:05,333] {/opt/conda-store/conda-store.py:170} INFO - polling interval set to 10 seconds
[2021-08-17 19:07:05,363] {/opt/conda-store/conda-store.py:129} INFO - building dashboard in /home/conda/environments/dashboard
[2021-08-17 19:07:05,363] {/opt/conda-store/conda-store.py:131} INFO - previously unfinished build of dashboard cleaning directory
~ ❯ kubectl logs -n qhub qhub-conda-store-7b74494c76-2gcdb conda-store -f               Py base ○ hubeu-qhub 12:09:01
[2021-08-17 19:07:05,333] {/opt/conda-store/conda-store.py:170} INFO - polling interval set to 10 seconds
[2021-08-17 19:07:05,363] {/opt/conda-store/conda-store.py:129} INFO - building dashboard in /home/conda/environments/dashboard
[2021-08-17 19:07:05,363] {/opt/conda-store/conda-store.py:131} INFO - previously unfinished build of dashboard cleaning directory
```
</details>

## Your environment

kubernetes: 1.18.19
qhub: 0.3.12 (and tested on `qhub@main`)
