### ISSUE TITLE
Create a plugin architecture

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#790]
Existing docs for plugins

https://docs.qhub.dev/en/latest/source/dev_guide/contribution.html#additions

**Comment by tylerpotts** [comment]
Per @danlester 

Related, here are my thoughts on how to distribute various private packages for QHub Enterprise: https://docs.google.com/document/d/12t-_RkXad-T_A2zWG91h1PDWL2qSHz37hk8s-EhxaLs/edit?usp=sharing (may need permissions to view)

Here is a possible qhub-config.yaml entry that might allow us to add an entirely new service based on a Docker image:

```
secrets:
  - name: githubtoken
     value: <github token>
extensions:
  - name: ent-control-panel
    image: ent-qhub/qhub-cp
    url: /control-panel
    admin: true
    secrets:
     - name: githubtoken
       envvar: github_token
```

This would add a service for the given image, and also add the /control-panel endpoint to traffic, directing to an agreed port (80). admin:true would mean it should be behind forwardauth middleware so only available to admins.

The given secret would also be mounted as an env var named github_token.

We also want to pass a secret through to the jupyterhub pod and also jupyterlab pods:
```
secrets:
  - name: elastechcustomer
    value: <customer id>
secretmounts:
  - name: elastechcustomer
    envvar: elastech_customer
    module: jupyterhub
  - name: elastechcustomer
    envvar: elastech_customer
    module: jupyterlab (?)
```

These env vars would be picked up by my versions of the jupyterhub theme, available in my custom jupyterhub image.

But I'm not sure how they would end up in jupyterlab pods launched by it. Either I just have to add code to jupyterhub to pass these on, or the extension mechanism also has a way to list env var names that should be passed through - this is quite specific to the jupyterhub service though.
