### ISSUE TITLE
Docs on how to better allocate resources for each cloud provider

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#796]
In administrative docs FAQ there should be a section/question about how to pick the correct memory/cpu for each cloud provider or in as many as we can find with links to the definitive docs.

**Comment by costrouc** [comment]
See https://github.com/Quansight/qhub/issues/792

**Comment by costrouc** [comment]
@viniciusdc please do a deep dive into this and try to get a formula for what the resources available are memory/cpu. Also try to test out these numbers with a blank slate gcp and digital ocean kubernetes clusters. That way we know that QHub is not causing the the issues with resources being taken up. Digtal ocean should be easier to work with. I would also just use the gui to spin up/down new instance types.

**Comment by costrouc** [comment]
You try to use a sample pod e.g. and try to schedule it on these clusters.

```yaml
...
kind: Pod
spec:
   containers:
       - name: busybox
         image: busybox:latest
         resources:
             ....
```

You'll have to play with the resources
