### ISSUE TITLE
[bug] Config to use the firstuseauthentificator in qhub

### ISSUE THREAD

**Issue by MarineChap** [Quansight/qhub#831]
(follow-up issue after asking this question of gitter)

I am trying to use the firstuseauthentificator in qhub.
my configuration looks like this : 
```
security:
  authentication:
    type: custom
    authentication_class: 'firstuseauthenticator.FirstUseAuthenticator'
    config: 
       min_password_length: 5

```
Then I run `python -m qhub deploy --config qhub-config.yaml` to update the deployment. (by the way is that the command I should use to update the deployment ? the doc is not super clear for this step.)

And the error displayed this : 
```
[terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 5m0s elapsed]
[terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 5m10s elapsed]
[terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 5m20s elapsed]
[terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 5m30s elapsed]
[terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 5m40s elapsed]
[terraform]: 
[terraform]: Error: timed out waiting for the condition
[terraform]: 
[terraform]:   on modules/kubernetes/services/jupyterhub/main.tf line 6, in resource "helm_release" "jupyterhub":
[terraform]:    6: resource "helm_release" "jupyterhub" {
[terraform]: 
[terraform]: 
```

Some advice on the config I should use would be nice ? Thanks !

Additional note if it can help : 
This is my config with the jupyterhub helm repo and it works: 
```
  hub:
    config:
     JupyterHub:
          authenticator_class: firstuseauthenticator.FirstUseAuthenticator
     FirstUseAuthenticator:
          min_password_length: 5
          admin_access: true
          admin_users: 
          - marine
```
## Your environment
qhub  == 0.3.12
minkube with kubernetes-version=1.19.4
jupyterhub-firstuseauthenticator == 0.14.1 (https://github.com/jupyterhub/firstuseauthenticator)

Thanks
