### ISSUE TITLE
Help Installing QHub on existing EKS (AWS) Cluster & Missing Local Testing Docs.

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#935]
Copying from email on behalf of @phobson
--------------------------------------------

We want to explore using QHub to manage our dask-cluster in our existing Kubernetes cluster in EKS. For that reason, we were reading this section of the installation guide:

https://docs.qhub.dev/en/stable/source/installation/setup.html#local-deployment-or-existing-kubernetes-cluster

That section links to the “Local Install Docs” (https://docs.qhub.dev/en/stable/source/development/testing.md#local-testing), but unfortunately that’s a dead link.

With that info unavailable, we kept moving forward through the tutorial explaining how to start from scratch, but trying to incorporate our existing cluster. To that end, we:

- Setup a repo on github
- Setup environment variables for my:
- Github Username
- Github Access Token (expires 30 days from today)
- AWS Secret Access Key
- AWS Access Key ID
- Setup Github OAuth for the URL associated with the API Server endpoint existing cluster as show in my AWS/EKS console (see below)
- used qhub init aws, following the prompts & double checking the input to successfully create a config file (attached)

From there, we tried qhub deploy -c qhub-config.yaml
 
Deployment fails as the EKS server endpoint returns a 403 status code when Terraform tries to hit it.

One potential issue is that we haven’t exposed our EKS cluster in AWS properly. We didn’t want to go too far down that road before getting confirmation that we are addressing this in the correct way.

So our question could be distilled down to the following:

- Is it possible to deploy to an existing EKS cluster and if so, how? We have the following EKS cluster details in the image below, just not sure which one we should be using.
- Do we need to setup a website (through Cloudflare for eg.) to correctly expose our AWS EKS cluster?

**Comment by dharhas** [comment]
@costrouc @aktech Are these the latest local install docs? 

Installing on minikube: https://docs.qhub.dev/en/stable/source/dev_guide/minikube.html?highlight=local%20install
Installing on local existing k8s: https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=local#local-existing-kubernetes-cluster

**Comment by phobson** [comment]
Thanks @dharhas

**Comment by iameskild** [comment]
Hi @phobson, thank you for you interest in QHub. I apologies that there are dead links in the docs, we are currently working to improve the docs in general. 

As for deploying QHub to an existing kubernetes cluster, I have successfully deployed QHub to an existing minikube cluster but have not yet tried doing so on an existing EKS cluster. From reading the docs and looking through the codebase, I'm not confident that doing so is possible; I will verify that this is the case with other devs. 

In the meantime, would you mind pasting a copy of your `qhub-config.yaml`? 
Thank you :)

**Comment by iameskild** [comment]
@phobson as a follow up to my previous comment, I've been told that deploying on an existing kubernetes cluster is possible (such as EKS) so long as the default `kubectl` context is properly set to the cluster you want to deploy on.

**Comment by phobson** [comment]
@iameskild 

Thanks for the info. 

My config file is here:
<details>

  ```yaml
  project_name: qhub-test
  provider: aws
  domain: https://0F9505330032D3FD25B933B44F218FCE.gr7.us-east-1.eks.amazonaws.com
  certificate:
    type: self-signed
  security:
    authentication:
      type: GitHub
      config:
        client_id: f1e30f346f79c67f0756
        client_secret: 72b00791333cd1d361a9a89488e66a0016aaaa79
        oauth_callback_url: https://0F9505330032D3FD25B933B44F218FCE.gr7.us-east-1.eks.amazonaws.com/hub/oauth_callback
    users:
      example-user:
        uid: 1000
        primary_group: admin
        secondary_groups:
        - users
    groups:
      users:
        gid: 100
      admin:
        gid: 101
  default_images:
    jupyterhub: quansight/qhub-jupyterhub:v0.3.13
    jupyterlab: quansight/qhub-jupyterlab:v0.3.13
    dask_worker: quansight/qhub-dask-worker:v0.3.13
    dask_gateway: quansight/qhub-dask-gateway:v0.3.13
    conda_store: quansight/qhub-conda-store:v0.3.13
  storage:
    conda_store: 60Gi
    shared_filesystem: 100Gi
  theme:
    jupyterhub:
      hub_title: QHub - None
      hub_subtitle: Autoscaling Compute Environment on Amazon Web Services
      welcome: Welcome to None. It is maintained by <a href="http://quansight.com">Quansight
        staff</a>. The hub's configuration is stored in a github repository based on
        <a href="https://github.com/Quansight/qhub/">https://github.com/Quansight/qhub/</a>.
        To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub/issues">github
        issue tracker</a>.
      logo: /hub/custom/images/jupyter_qhub_logo.svg
      primary_color: '#4f4173'
      secondary_color: '#957da6'
      accent_color: '#32C574'
      text_color: '#111111'
      h1_color: '#652e8e'
      h2_color: '#652e8e'
  monitoring:
    enabled: true
  cdsdashboards:
    enabled: true
    cds_hide_user_named_servers: true
    cds_hide_user_dashboard_servers: false
  terraform_state:
    type: remote
  namespace: dev
  amazon_web_services:
    region: us-west-2
    kubernetes_version: '1.18'
    node_groups:
      general:
        instance: m5.xlarge
        min_nodes: 1
        max_nodes: 1
      user:
        instance: m5.large
        min_nodes: 1
        max_nodes: 5
      worker:
        instance: m5.large
        min_nodes: 1
        max_nodes: 5
  profiles:
    jupyterlab:
    - display_name: Small Instance
      description: Stable environment with 1 cpu / 4 GB ram
      default: true
      kubespawner_override:
        cpu_limit: 1
        cpu_guarantee: 0.75
        mem_limit: 4G
        mem_guarantee: 2.5G
        image: quansight/qhub-jupyterlab:v0.3.13
    - display_name: Medium Instance
      description: Stable environment with 2 cpu / 8 GB ram
      kubespawner_override:
        cpu_limit: 2
        cpu_guarantee: 1.5
        mem_limit: 8G
        mem_guarantee: 5G
        image: quansight/qhub-jupyterlab:v0.3.13
    dask_worker:
      Small Worker:
        worker_cores_limit: 1
        worker_cores: 0.75
        worker_memory_limit: 4G
        worker_memory: 2.5G
        worker_threads: 1
        image: quansight/qhub-dask-worker:v0.3.13
      Medium Worker:
        worker_cores_limit: 2
        worker_cores: 1.5
        worker_memory_limit: 8G
        worker_memory: 5G
        worker_threads: 2
        image: quansight/qhub-dask-worker:v0.3.13
  environments:
    environment-dask.yaml:
      name: dask
      channels:
      - conda-forge
      dependencies:
      - python
      - ipykernel
      - ipywidgets
      - qhub-dask ==0.3.13
      - python-graphviz
      - numpy
      - numba
      - pandas
    environment-dashboard.yaml:
      name: dashboard
      channels:
      - conda-forge
      dependencies:
      - python==3.9.7
      - ipykernel==6.4.1
      - ipywidgets==7.6.5
      - qhub-dask==0.3.13
      - param==1.11.1
      - python-graphviz==0.17
      - matplotlib==3.4.3
      - panel==0.12.4
      - voila==0.2.16
      - streamlit==1.0.0
      - dash==2.0.0
      - cdsdashboards-singleuser==0.5.7
  ```

</details>

I'm far from even being conversant in a lot of these tools. There are a some challenges I see for me and my team to get this running on our system. First thing I'm seeing is that our team develops our product on Windows and have all of our e.g., `kubectl` auth tokens/port forwarding setup for Windows.

My attempts at getting Qhub going last week were on Windows Subsystem for Linux. (WSL). I'm fairly comfortable with unix-like systems, but a worry I have is that I'll need to do quite a bit of prep work to get everything configured and authorized on the WSL side before we can move forward with additional troubleshooting.

I'm gonna reach out to my team re: our `kubectl` setup and report back.
