### ISSUE TITLE
project field no longer needed for azure in qhub-config [enhancement]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#961]
## Description

There is historically a `project` field in the `qhub-config.yaml` schema for Azure:

```
azure:
  project: PLACEHOLDER
  region: Central US
  kubernetes_version: 1.19.11
  node_groups:
    general:
      instance: Standard_D4_v3
      min_nodes: 1
      max_nodes: 1
    user:
      instance: Standard_D2_v2
      min_nodes: 0
      max_nodes: 5
    worker:
      instance: Standard_D2_v2
      min_nodes: 0
      max_nodes: 5
  storage_account_postfix: t65ft6q5
```

I believe this was never needed (copied from GCP's entry inadvertently) so can be removed.

## Value/benefit

Simplify config and increase avoid confusion.

### If the request is related to a specific version of Kubernetes or Cloud provider

Azure
