### ISSUE TITLE
kubernetes overrides with jupyterhub profiles are stateful

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#969]
## Describe the bug

 - currently when you use a given key in jupyterhub as a kubernetes override it then gets set as the default value. This is wront 

```
  - display_name: Large Instance
    description: Stable environment with 8 cpu / 32 GB ram
    kubespawner_override:
      cpu_limit: 8
      cpu_guarantee: 7.25
      mem_limit: 32G
      mem_guarantee: 24G
      image: quansight/qhub-jupyterlab:v0.3.14
  - display_name: Large GPU Instance
    description: Stable environment with 8 cpu / 32 GB ram and 1 Nvidia Tesla T4
    kubespawner_override:
      cpu_limit: 8
      cpu_guarantee: 7.25
      mem_limit: 32G
      mem_guarantee: 24G
      image: quansight/qhub-jupyterlab:v0.3.14
      extra_resource_limits:
        nvidia.com/gpu: 1
      node_selector:
          "cloud.google.com/gke-nodepool": "gpu-tesla-t4"
```

## Expected behaviour

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

## Actual behaviour

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### OS

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### Dependencies

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
